[package]
name = "backend-api-jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
bcrypt = "0.17.1"
chrono = "0.4.42"
dotenvy = "0.15"
jsonwebtoken = "10.2.0"
serde = "1.0.228"
serde_json = "1.0.148"
sqlx = "0.8.6"
tokio = "1.48.0"
tower-http = "0.6.8"
validator = "0.20.0"
